Repository Vyctor661/king-typer, pull requests merged in 2020-07, with the labels that each got.

#16 Auth
  .eslintrc
  .vscode/settings.json
  packages/api/db/migrations/20200608182453_create_users_table.ts
  packages/api/db/migrations/20200627153355_create-sessions.ts
  packages/api/db/migrations/20200705082902_create_games_table.ts
  packages/api/db/seeds/examples/users.ts
  packages/api/db/seeds/users.ts
  packages/api/knexfile.ts
  packages/api/nodemon.json
  packages/api/package.json
  packages/api/register.js
  packages/api/src/common/error/classes/httpError.ts
  packages/api/src/index.ts
  packages/api/src/modules/Router.ts
  packages/api/src/modules/apiRouter.ts
  packages/api/src/modules/auth/middleware/requireAdmin.ts
  packages/api/src/modules/auth/middleware/requireAuthenticated.ts
  packages/api/src/modules/auth/middleware/requireUnauthenticated.ts
  packages/api/src/modules/auth/router.test.ts
  packages/api/src/modules/auth/router.ts
  packages/api/src/modules/auth/schema/loginBody.ts
  packages/api/src/modules/auth/types/LoginBody.ts
  packages/api/src/modules/cors/middleware/allowCors.ts
  packages/api/src/modules/schema/middleware/validateSchema.ts
  packages/api/src/modules/session/actions/destroyCookie.ts
  packages/api/src/modules/session/actions/getCookie.ts
  packages/api/src/modules/session/actions/setCookie.ts
  packages/api/src/modules/session/helpers/useSession.ts
  packages/api/src/modules/session/types/Session.ts
  packages/api/src/modules/users/actions/createUser.ts
  packages/api/src/modules/users/actions/findUser.ts
  packages/api/src/modules/users/router.test.ts
  packages/api/src/modules/users/router.ts
  packages/api/src/modules/users/schema/registerBody.ts
  packages/api/src/modules/users/types/RegisterBody.ts
  packages/api/src/modules/users/types/User.ts
  packages/api/tsconfig.json
  packages/web/src/components/common/typingBox/helpers/gettext.ts
  packages/web/src/utils/randomText.ts
  pnpm-lock.yaml
Labels: enhancement

#23 Achievements
  packages/api/db/migrations/20200711075708_add_achievements_to_users.ts
  packages/api/db/migrations/20200711080224_create-achievements.ts
  packages/api/db/seeds/achievements.ts
  packages/api/db/seeds/examples/achievements.ts
  packages/api/db/seeds/examples/users.ts
  packages/api/register.js
  packages/api/src/modules/achievements/actions/achievementMatches.ts
  packages/api/src/modules/achievements/actions/addAchievement.ts
  packages/api/src/modules/achievements/actions/compareRequirements.ts
  packages/api/src/modules/achievements/actions/deleteAchievement.ts
  packages/api/src/modules/achievements/actions/editAchievement.ts
  packages/api/src/modules/achievements/actions/findAchievementsByRequirement.ts
  packages/api/src/modules/achievements/actions/getAchievements.ts
  packages/api/src/modules/achievements/actions/userHasAchievement.ts
  packages/api/src/modules/achievements/router.test.ts
  packages/api/src/modules/achievements/router.ts
  packages/api/src/modules/achievements/types/Achievement.ts
  packages/api/src/modules/achievements/types/Requirement.ts
  packages/api/src/modules/apiRouter.ts
  packages/api/src/modules/auth/router.test.ts
  packages/api/src/modules/games/actions/createGame.ts
  packages/api/src/modules/games/router.test.ts
  packages/api/src/modules/users/actions/createUser.ts
  packages/api/src/modules/users/actions/userAchievements.ts
  packages/api/src/modules/users/router.test.ts
  packages/api/src/modules/users/router.ts
  packages/api/src/modules/users/types/User.ts
  pnpm-lock.yaml
Labels: enhancement

#32 Email
  packages/api/db/migrations/20200712085743_add_emailkey.ts
  packages/api/db/seeds/examples/users.ts
  packages/api/package.json
  packages/api/src/modules/apiRouter.ts
  packages/api/src/modules/email/actions/generateVerification.ts
  packages/api/src/modules/email/actions/sendVerificationEmail.ts
  packages/api/src/modules/email/router.test.ts
  packages/api/src/modules/email/router.ts
  packages/api/src/modules/users/actions/createUser.ts
  packages/api/src/modules/users/actions/updateUserRole.ts
  packages/api/src/modules/users/actions/verifyUserEmail.ts
  packages/api/src/modules/users/types/User.ts
  pnpm-lock.yaml
Labels: enhancement

#33 feat: forgot password stuff (huge commit)
  packages/api/db/migrations/20200713095514_create_forgot_passwords.ts
  packages/api/src/modules/users/actions/forgotPassword.ts
  packages/api/src/modules/users/router.test.ts
  packages/api/src/modules/users/router.ts
Labels: enhancement

#40 Revert "Texts"
  packages/api/db/migrations/20200716182227_add_difficulty_to_games.ts
  packages/api/db/migrations/20200716182727_add_text_id_to_games.ts
  packages/api/db/migrations/20200716185527_alter_games_table.ts
  packages/api/db/migrations/20200716191304_add_textid_difficulty_to_pbs.ts
  packages/api/db/migrations/20200716191859_alter_pbs_table.ts
  packages/api/src/modules/games/actions/createGame.ts
  packages/api/src/modules/games/router.test.ts
  packages/api/src/modules/games/router.ts
  packages/web/src/components/common/typingBox/components/progressbar/progressBar.tsx
  packages/web/src/components/common/typingBox/components/progressbar/style.tsx
  packages/web/src/components/common/typingBox/helpers/interfaces.ts
  packages/web/src/components/common/typingBox/style.tsx
  packages/web/src/components/common/typingBox/typingBox.tsx
  packages/web/src/components/frontPage/home.tsx
  packages/web/src/components/profilePage/helpers/interfaces.ts
  packages/web/src/components/profilePage/profilePage.tsx
  packages/web/src/components/startTypingPage/startTypingPage.tsx
Labels: api, bug

#41 Texts (fixing tests)
  packages/api/db/migrations/20200716182227_add_difficulty_to_games.ts
  packages/api/db/migrations/20200716182727_add_text_id_to_games.ts
  packages/api/db/migrations/20200716185527_alter_games_table.ts
  packages/api/db/migrations/20200716191304_add_textid_difficulty_to_pbs.ts
  packages/api/db/migrations/20200716191859_alter_pbs_table.ts
  packages/api/src/modules/games/actions/createGame.ts
  packages/api/src/modules/games/router.test.ts
  packages/api/src/modules/games/router.ts
  packages/api/src/modules/games/schema/newGameBody.ts
  packages/api/src/modules/texts/router.test.ts
  packages/api/src/modules/users/actions/forgotPassword.ts
  packages/api/src/modules/users/router.test.ts
  packages/web/src/components/common/typingBox/components/progressbar/progressBar.tsx
  packages/web/src/components/common/typingBox/components/progressbar/style.tsx
  packages/web/src/components/common/typingBox/helpers/interfaces.ts
  packages/web/src/components/common/typingBox/style.tsx
  packages/web/src/components/common/typingBox/typingBox.tsx
  packages/web/src/components/frontPage/home.tsx
  packages/web/src/components/profilePage/helpers/interfaces.ts
  packages/web/src/components/profilePage/profilePage.tsx
  packages/web/src/components/startTypingPage/startTypingPage.tsx
Labels: api, bug, enhancement, fe

#45 Achievements
  packages/api/src/modules/achievements/actions/compareRequirements.ts
  packages/api/src/modules/games/actions/createGame.ts
Labels: enhancement

#47 Multiplayer
  packages/api/package.json
  packages/api/src/index.ts
  packages/api/src/modules/email/router.test.ts
  packages/api/src/modules/games/actions/createMultiGame.ts
  packages/api/src/modules/games/actions/removeOldGame.ts
  packages/api/src/modules/games/types/Game.ts
  packages/api/src/modules/websockets/actions/gameFinished.ts
  packages/api/src/modules/websockets/actions/joinQueue.ts
  packages/api/src/modules/websockets/actions/leaveQueue.ts
  packages/api/src/modules/websockets/actions/processClose.ts
  packages/api/src/modules/websockets/actions/processQueue.ts
  packages/api/src/modules/websockets/actions/pruneGames.ts
  packages/api/src/modules/websockets/actions/switchQueueLocation.ts
  packages/api/src/modules/websockets/actions/updateProgress.ts
  packages/api/src/modules/websockets/gamesData.ts
  packages/api/src/modules/websockets/middleware/categoryParser.ts
  packages/api/src/modules/websockets/types/Category.ts
  packages/api/src/modules/websockets/types/HandlerResponse.ts
  packages/api/src/modules/websockets/websocket.ts
  packages/api/tsconfig.json
  packages/web/package.json
  packages/web/src/components/common/typingBox/components/progressbar/progressBar.tsx
  packages/web/src/components/common/typingBox/helpers/gettext.ts
  packages/web/src/components/common/typingBox/helpers/interfaces.ts
  packages/web/src/components/common/typingBox/style.tsx
  packages/web/src/components/common/typingBox/typingBox.tsx
  packages/web/src/components/frontPage/home.tsx
  packages/web/src/components/profilePage/profilePage.tsx
  packages/web/src/components/startTypingPage/helpers/websocket.ts
  packages/web/src/components/startTypingPage/startTypingPage.tsx
  packages/web/src/utils/constants.ts
  packages/web/src/utils/getTheme.ts
  packages/web/src/utils/websocket.ts
  pnpm-lock.yaml
Labels: api, enhancement, fe

#53 Docs
  docs/en/about.md
  docs/en/assets-&-code-i-dont-own.md
  docs/en/basic-usage.md
  docs/en/main.md
  docs/en/tutorials/instalation.md
  docs/en/tutorials/installation.md
  docs/en/tutorials/touch-typing.md
  docs/ro/assets-&-cod-pe-care-nu-il-detin.md
  docs/ro/despre.md
  docs/ro/main.md
  docs/ro/tutoriale/instalare.md
  docs/ro/tutoriale/touch-typing.md
  docs/ro/utilizare.md
Labels: documentation
